noetic_mysql:
  extends:
    file: docker-compose.yml
    service: noetic_mysql 
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}/tmp/var/lib/mysql:/var/lib/mysql   
    
    
noetic_web:
  build: ${IMERIAL_FRONTEND_ROOT_PATH}
  container_name: noetic_web
  ports:
    - 80:80
    - 443:443
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}:/local
  links:
    - noetic_mysql
    - noetic_redis
  # env vars are replace into /cms/craft/config
  environment:
    LANG: C.UTF-8
    
noetic_redis:
  image: redis:3.2.6
  container_name: noetic_redis
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}/docker/includes/usr/local/etc/redis:/usr/local/etc/redis
    - ${IMERIAL_FRONTEND_ROOT_PATH}/tmp/ar/lib/redis:/var/lib/redis
  ports:
    - 6379:6379
  command: redis-server /usr/local/etc/redis/redis.conf       