noetic_mysql_frontend: 
  build: ./mysql
  container_name: noetic_mysql_frontend
  env_file:
     - ./.env    
  ports:
    - 3306:3306  
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PWD}
    MYSQL_DATABASE: ${MYSQL_CRAFT_DB_NAME}
    MYSQL_USER: ${MYSQL_DB_USER}
    MYSQL_PASSWORD: ${MYSQL_DB_PWD}
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}/tmp/var/lib/mysql:/var/lib/mysql   
    
    
noetic_web:
  build: ${IMERIAL_FRONTEND_ROOT_PATH}
  container_name: noetic_web
  env_file:
     - ./.env    
  ports:
    - 80:80
    - 443:443
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}:/local
  links:
    - noetic_mysql_frontend
    - noetic_redis
  # env vars are replace into /cms/craft/config
  environment:
    LANG: C.UTF-8
    
noetic_redis:
  image: redis:3.2.6
  container_name: noetic_redis
  env_file:
     - ./.env    
  volumes:
    - ${IMERIAL_FRONTEND_ROOT_PATH}/docker/includes/usr/local/etc/redis:/usr/local/etc/redis
    - ${IMERIAL_FRONTEND_ROOT_PATH}/tmp/ar/lib/redis:/var/lib/redis
  ports:
    - 6379:6379
  command: redis-server /usr/local/etc/redis/redis.conf       