noetic_tomcat:
  build: ./tomcat
  container_name: noetic_tomcat
  env_file:
     - ./.env  
  volumes:
    - "${TARGET_FOLDER}:/usr/local/tomcat/webapps/ROOT"
  links:
    - noetic_mysql:localhost
  ports:
    - 8080:8080
    - 8787:8787
  environment:
    - JAVA_OPTS=-Xms128m -Xmx1024m -XX:MaxPermSize=256m -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n -DdeployProfile=${DEPLOY_PROFILE}     

noetic_mysql:
  build: ./mysql
  container_name: noetic_mysql
  env_file:
     - ./.env    
  ports:
    - 3306:3306  
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PWD}
    MYSQL_DATABASE: ${MYSQL_DB_NAME}
    MYSQL_USER: ${MYSQL_DB_USER}
    MYSQL_PASSWORD: ${MYSQL_DB_PWD}