version: "3.3"
services:

  noetic_tomcat:
      build: .
      container_name: noetic_tomcat
      env_file:
         - ./.env
      volumes:
        - "${TARGET_FOLDER}:/usr/local/tomcat/webapps"
      links:
        - noetic_mysql:localhost
      ports:
        - 8080:8080
      environment:
        - JAVA_OPTS=-Xms128m -Xmx1024m -DdeployProfile=LOCAL      
      networks:
        - docker_network          
  
  noetic_mysql:
      build: ./mysql
      container_name: noetic_mysql
      env_file:
         - ./.env  
      ports:
        - 3306:3306  
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PWD}
        MYSQL_DATABASE: ${MYSQL_DB_NAME}
        MYSQL_USER: ${MYSQL_DB_USER}
        MYSQL_PASSWORD: ${MYSQL_DB_PWD}
      networks:
        - docker_network
 
 
networks:
  docker_network:
    driver: bridge